--- # Test Loops

- hosts: appgroup
  user: ansadm
  connection: ssh
  sudo: yes
  gather_facts: no
  tasks:
  - name: Add List of Users to server
    user: name={{ item }} state=present
    with_items:
    - user1
    - user2
    - user3
